export * from "./AgeSvg";
export * from "./AlcoholSvg";
export * from "./BloodSvg";
export * from "./BodyWeightSvg";
export * from "./CallSvg";
export * from "./DonorHeartSvg";
export * from "./FilterSvg";
export * from "./HeartBeatSvg";
export * from "./HospitalSvg";
export * from "./IDSvg";
export * from "./LocationSvg";
export * from "./NoFoodSvg";
export * from "./PillSvg";
export * from "./SurgerySvg";
export * from "./TattooSvg";
export * from "./VaccineSvg";
export * from "./VirusSvg";
export * from "./WhatsAppSvg";

